# Generated by Django 5.2.7 on 2026-02-09 06:34

import cloudinary.models
import rebbletapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rebbletapp", "0003_alter_mediamodel_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediamodel",
            name="media",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                null=True,
                validators=[rebbletapp.models.validate_media_size],
                verbose_name="media",
            ),
        ),
    ]
