# Generated by Django 5.2.7 on 2026-02-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rebbletapp", "0005_alter_mediamodel_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediamodel",
            name="media_type_field",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="mediamodel",
            name="media_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
