# Generated by Django 5.2.7 on 2026-02-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rebbletapp", "0006_mediamodel_media_type_field_mediamodel_media_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediamodel",
            name="media_url",
            field=models.URLField(blank=True, max_length=1000, unique=True),
        ),
    ]
